site_name: Argo Cluster Bootstrapping
theme:
  name: 'material'
docs_dir: docs/
repo_name: 'nolte/gh-plumbing'
repo_url: 'https://github.com/nolte/gh-plumbing'
markdown_extensions:
  - toc:
      permalink: True
extra_css:
  - css/overwrite.css
