apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
  
resources:
   - https://raw.githubusercontent.com/projectcontour/contour/main/examples/contour/01-crds.yaml
  #- https://raw.githubusercontent.com/bitnami/charts/master/bitnami/contour/resources/extensionservices.yaml
  #- https://raw.githubusercontent.com/bitnami/charts/master/bitnami/contour/resources/httpproxies.yaml
  #- https://raw.githubusercontent.com/bitnami/charts/master/bitnami/contour/resources/tlscertificatedeligations.yaml