# https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/values.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring
  namespace: {{ .Release.Namespace }} 
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  project: default
  source:
    path: kube-prometheus-stack
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: HEAD
    helm:
      releaseName: monitoring
      #values: >


  syncPolicy:
    automated:
      prune: true
      selfHeal: true