# https://github.com/argoproj/argo-helm/blob/master/charts/argo-cd/values.yaml
argo-cd:
  installCRDs: false
  repoServer:
  # 2. Use an init container to download/copy custom binaries into the emptyDir
    volumes:
    - name: custom-tools
      emptyDir: {}
    initContainers:
    - name: download-tools-kustomize
      image: alpine:3.8
      command: [sh, -c]
      args:
        - wget -qO- https://github.com/kubernetes-sigs/kustomize/releases/download/kustomize%2Fv3.9.2/kustomize_v3.9.2_linux_amd64.tar.gz | tar -xvzf - &&
          mv kustomize /custom-tools/kustomize_3_9_2 &&
          chmod +x /custom-tools/kustomize_3_9_2
      volumeMounts:
        - mountPath: /custom-tools
          name: custom-tools
    - name: download-tools-helm
      image: alpine:3.8
      command: [sh, -c]
      args:
        - wget -qO- https://get.helm.sh/helm-v3.5.1-linux-amd64.tar.gz | tar -xvzf - &&
          mv linux-amd64/helm /custom-tools/helm_3_5_1
      volumeMounts:
        - mountPath: /custom-tools
          name: custom-tools
    volumeMounts:
    - mountPath: /custom-tools
      name: custom-tools
  global:
    image:
      tag: v1.8.3
  server:
    #volumeMounts:
    #  - mountPath: /usr/local/bin/helm
    #    name: custom-tools
    #    subPath: helm  
    additionalProjects:
      - name: default
        namespace: argocd
        description: Baseline Relevant Projects
        clusterResourceWhitelist:
        - group: '*'
          kind: '*'
        destinations:
        - namespace: '*'
          server: '*'
        sourceRepos:
        - '*'
      - name: baseline
        namespace: argocd
        description: Baseline Relevant Projects
        clusterResourceWhitelist:
        - group: '*'
          kind: '*'
        destinations:
        - namespace: '*'
          server: '*'
        sourceRepos:
        - '*'
      - name: cicd
        namespace: argocd
        description: CICD Tools
        clusterResourceWhitelist:
        - group: '*'
          kind: '*'
        destinations:
        - namespace: '*'
          server: '*'
        sourceRepos:
        - '*'
    config:
      kustomize.version.v3.9.2: /custom-tools/kustomize_3_9_2
      helm.version.v3.5.1: /custom-tools/helm_3_5_1      
      resource.customizations: |
        admissionregistration.k8s.io/MutatingWebhookConfiguration:
          ignoreDifferences: |
            jsonPointers:
            - /webhooks/0/failurePolicy
        admissionregistration.k8s.io/ValidatingWebhookConfiguration:
          ignoreDifferences: |
            jsonPointers:
            - /webhooks/0/failurePolicy
        apiextensions.k8s.io/CustomResourceDefinition:
          ignoreDifferences: |
            jsonPointers:
            - /spec/0/preserveUnknownFields
            - /spec/preserveUnknownFields
      repositories: |
        - type: helm
          url: https://argoproj.github.io/argo-helm
          name: argo
        - type: helm
          url: https://prometheus-community.github.io/helm-charts
          name: prometheus-community
        - type: helm
          url: https://charts.bitnami.com/bitnami
          name: bitnami
        - type: helm
          url: https://charts.jetstack.io
          name: jetstack
        - type: helm
          url: https://helm.min.io/
          name: minio
        - type: helm
          url: https://nolte.github.io/argo-charts/
          name: argo-charts
        - type: helm
          url: https://halkeye.github.io/helm-charts/
          name: halkeye
