apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: seed-argo
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: in-cluster
    namespace: argocd
  project: seed
  source:
    repoURL: https://nolte.github.io/argo-charts/
    targetRevision: 1.6.0
    chart: argo-cd
    helm:
      releaseName: argocd
      version: v3.5.1
  syncPolicy: {}
#    automated: {}
#      prune: true
#      selfHeal: true