apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

patches:
  - path: sync-patch.yaml
    target:
      kind: Application
  #- path: patch-helm-release.yaml
  #  target:
  #    kind: Application
  #    name: baseline

resources:
  - ../base
  #- ../devops
  - cluster-issuer.yaml