apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{.Values.prefix}}ingress
  namespace: {{ .Release.Namespace }} 
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: {{ .Values.destinationName }}
    namespace: argocd
  project: baseline
  source:
    path: charts/app-of-app
    repoURL: https://github.com/nolte/argo-bootstrap.git
    targetRevision: HEAD
    helm:
      values: |
        project: baseline
        destinationName: {{ .Values.destinationName }}
        depoymentDestinationName: {{ .Values.depoymentDestinationName }}
        applications:
          # https://github.com/bitnami/charts/blob/master/bitnami/contour/values.yaml
          {{.Values.prefix}}contour:
            namespace: projectcontour
            syncPolicyAutomated:
              prune: true
              selfHeal: true
            source:
              chart: contour
              repoURL: https://charts.bitnami.com/bitnami
              targetRevision: 4.1.0
              helm:
                values: |
                  prometheus:
                    serviceMonitor:
                      enabled: true
                  envoy:
                    service:
                      type: NodePort
                  contour:
                    manageCRDs: true
                version: v3
          # https://artifacthub.io/packages/helm/jetstack/cert-manager    
          # https://github.com/jetstack/cert-manager/blob/master/deploy/charts/cert-manager/values.yaml
          {{.Values.prefix}}cert-manager:
            namespace: cert-manager
            syncPolicyAutomated:
              prune: true
              selfHeal: true
            source:
              chart: cert-manager
              repoURL: https://charts.jetstack.io
              targetRevision: v1.1.0
              helm:
                values: |
                  prometheus:
                    enabled: true
                    servicemonitor:
                      enabled: true
          {{.Values.prefix}}forecastle:
            namespace: opreators
            syncPolicyAutomated:
              prune: true
              selfHeal: true
            source:
              path: deployments/kubernetes/chart/forecastle/
              repoURL: https://github.com/stakater/Forecastle
              targetRevision: v1.0.62
          {{.Values.prefix}}reloader:
            namespace: opreators
            syncPolicyAutomated:
              prune: true
              selfHeal: true
            source:
              path: deployments/kubernetes/chart/reloader/
              repoURL: https://github.com/stakater/Reloader
              targetRevision: v0.0.79
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
