apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring
  namespace: {{ .Release.Namespace }} 
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  project: default
  source:
    path: charts/app-of-app
    repoURL: https://github.com/nolte/argo-bootstrap.git
    targetRevision: HEAD
    helm:
      releaseName: monitoring
      values: |
        project: baseline
        applications:
          kube-prometheus-stack:
            namespace: monitoring
            source:
              chart: kube-prometheus-stack
              repoURL: https://prometheus-community.github.io/helm-charts
              targetRevision: 13.4.1
              helm:
                releaseName: monitoring
                values: |
                  grafana:
                    enabled: false                   
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
