apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: baseline
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: in-cluster
    namespace: argocd
  project: default
  source:
    path: src/charts/technical/collection-baseline
    repoURL: https://github.com/nolte/argo-bootstrap.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true