apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: baseline
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: in-cluster
    namespace: argocd
  project: default
  source:
    #path: src/charts/technical/collection-baseline
    #chart: project-contour
    #repoURL: https://nolte.github.io/argo-charts/
    #targetRevision: 1.2.0
    repoURL: https://github.com/nolte/argo-bootstrap
    targetRevision: head
    path: src/charts/technical/collection-baseline
    helm:
      releaseName: contour
      version: v3.5.1
  syncPolicy: {}
#    automated: {}
#      prune: true
#      selfHeal: true