apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: anyName
spec:
  source:
    helm:
      values: |
        project-contour:
          destination:
            name: kind-production
        cert-manager:
          destination:
            name: kind-production
        monitoring:
          destination:
            name: kind-production
        forecastle:
          destination:
            name: kind-production
        konfigurator:
          destination:
            name: kind-production
        reloader:
          destination:
            name: kind-production