apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

#https://kubectl.docs.kubernetes.io/references/kustomize/nameprefix/
namePrefix: prod-
namespace: argocd

commonLabels:
  just-mfg.de/appgroup: prd

patches:
  - path: destination-patch.yaml
    target:
      kind: Application
  - path: sync-patch.yaml
    target:
      kind: Application
  - path: patch-helm-release.yaml
    target:
      kind: Application
      name: baseline

resources:
  - ../base